"""empty message

Revision ID: 1ccc16a6b4fb
Revises: None
Create Date: 2015-04-17 23:39:02.313748

"""

# revision identifiers, used by Alembic.
revision = '1ccc16a6b4fb'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
