"""empty message

Revision ID: 2314cd6f72dc
Revises: 75f0029684b
Create Date: 2015-04-18 11:14:30.339222

"""

# revision identifiers, used by Alembic.
revision = '2314cd6f72dc'
down_revision = '75f0029684b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
